BEGIN;

INSERT INTO tracker.taxonomy_versions (version_code,name,effective_date,status,description)
VALUES ('TAXONOMY-1.0','Master Research Taxonomy Version 1.0','2014-01-01','active','Canonical taxonomy from Master Research Taxonomy and Data Model v1.0');

INSERT INTO tracker.governments (code,name,leader,start_date,end_date,status) VALUES
('MODI_I','Modi I','Narendra Modi','2014-05-26','2019-05-29','historical'),
('MODI_II','Modi II','Narendra Modi','2019-05-30','2024-06-08','historical'),
('MODI_III','Modi III','Narendra Modi','2024-06-09',NULL,'active');

INSERT INTO tracker.government_terms (term_code,name,government_id,start_date,end_date,status,display_order)
SELECT 'MODI_I','Modi I',government_id,'2014-05-26','2019-05-29','historical',1 FROM tracker.governments WHERE code='MODI_I';
INSERT INTO tracker.government_terms (term_code,name,government_id,start_date,end_date,status,display_order)
SELECT 'MODI_II','Modi II',government_id,'2019-05-30','2024-06-08','historical',2 FROM tracker.governments WHERE code='MODI_II';
INSERT INTO tracker.government_terms (term_code,name,government_id,start_date,end_date,status,display_order)
SELECT 'MODI_III','Modi III',government_id,'2024-06-09',NULL,'active',3 FROM tracker.governments WHERE code='MODI_III';
INSERT INTO tracker.government_terms (term_code,name,start_date,end_date,status,display_order)
VALUES ('OVERALL_2014_PRESENT','Overall 2014-present','2014-01-01',NULL,'open',4);

INSERT INTO tracker.countries (code,name,status) VALUES ('IND','India','active');
INSERT INTO tracker.geographies (geography_code,geography_type,country_id,name,status)
SELECT 'INDIA','india',country_id,'India','active' FROM tracker.countries WHERE code='IND';

INSERT INTO tracker.states (code,name,state_type,status) VALUES
('AP','Andhra Pradesh','state','active'),('AR','Arunachal Pradesh','state','active'),('AS','Assam','state','active'),('BR','Bihar','state','active'),
('CG','Chhattisgarh','state','active'),('GA','Goa','state','active'),('GJ','Gujarat','state','active'),('HR','Haryana','state','active'),
('HP','Himachal Pradesh','state','active'),('JH','Jharkhand','state','active'),('KA','Karnataka','state','active'),('KL','Kerala','state','active'),
('MP','Madhya Pradesh','state','active'),('MH','Maharashtra','state','active'),('MN','Manipur','state','active'),('ML','Meghalaya','state','active'),
('MZ','Mizoram','state','active'),('NL','Nagaland','state','active'),('OD','Odisha','state','active'),('PB','Punjab','state','active'),
('RJ','Rajasthan','state','active'),('SK','Sikkim','state','active'),('TN','Tamil Nadu','state','active'),('TS','Telangana','state','active'),
('TR','Tripura','state','active'),('UP','Uttar Pradesh','state','active'),('UK','Uttarakhand','state','active'),('WB','West Bengal','state','active'),
('AN','Andaman and Nicobar Islands','union_territory','active'),('CH','Chandigarh','union_territory','active'),
('DNDD','Dadra and Nagar Haveli and Daman and Diu','union_territory','active'),('DL','Delhi','union_territory','active'),
('JK','Jammu and Kashmir','union_territory','active'),('LA','Ladakh','union_territory','active'),('LD','Lakshadweep','union_territory','active'),
('PY','Puducherry','union_territory','active');

INSERT INTO tracker.geographies (geography_code,geography_type,country_id,state_id,name,status)
SELECT s.code, CASE WHEN s.state_type='state' THEN 'state' ELSE 'union_territory' END, c.country_id, s.state_id, s.name, 'active'
FROM tracker.states s CROSS JOIN tracker.countries c WHERE c.code='IND';

INSERT INTO tracker.sectors (code,name,taxonomy_version_id,status)
SELECT v.code,v.name,tv.taxonomy_version_id,'active'
FROM (VALUES
('MACRO','Macroeconomy'),('PUBLIC_FIN','Public Finance'),('TAX','Taxation'),('BFS','Banking and Financial Services'),
('MFG','Manufacturing'),('MSME','MSMEs'),('AGRI','Agriculture'),('RURAL','Rural Economy'),('SRV','Services'),
('DIGITAL','Digital Economy'),('STARTUPS','Startups and Entrepreneurship'),('TRADE','Trade and Exports'),('INVEST','Investment'),
('LABOUR','Employment and Labour'),('INFRA','Infrastructure'),('ENERGY','Energy'),('TELECOM','Telecom'),('HEALTH','Healthcare'),
('EDU','Education'),('HOUSING','Housing'),('WATER','Water and Sanitation'),('STI','Science, Technology and Innovation'),('SPACE','Space'),
('DEFENCE','Defence'),('ENV','Environment and Climate'),('TOURISM','Tourism'),('SOCIAL','Social Protection'),('POVERTY','Poverty and Living Standards'),
('WOMEN','Women and Economic Participation'),('DEMOGRAPHICS','Demographics'),('GOV','Governance and Institutions'),
('LEGAL','Legal and Judicial Framework'),('GLOBAL','Global Position')) AS v(code,name)
CROSS JOIN tracker.taxonomy_versions tv WHERE tv.version_code='TAXONOMY-1.0';

INSERT INTO tracker.sub_sectors (sector_id,code,name,taxonomy_version_id,status)
SELECT s.sector_id,v.code,v.name,tv.taxonomy_version_id,'active'
FROM (VALUES
('MACRO','SUB-MACRO-001','GDP'),('MACRO','SUB-MACRO-002','GVA'),('MACRO','SUB-MACRO-003','National Income'),('MACRO','SUB-MACRO-004','Per-Capita Income'),('MACRO','SUB-MACRO-005','Consumption'),('MACRO','SUB-MACRO-006','Savings'),('MACRO','SUB-MACRO-007','Investment'),('MACRO','SUB-MACRO-008','Gross Fixed Capital Formation'),('MACRO','SUB-MACRO-009','Productivity'),('MACRO','SUB-MACRO-010','Inflation'),('MACRO','SUB-MACRO-011','Interest Rates'),('MACRO','SUB-MACRO-012','External Sector'),('MACRO','SUB-MACRO-013','Business Cycles'),('MACRO','SUB-MACRO-014','Economic Growth'),
('PUBLIC_FIN','SUB-PUBLIC_FIN-001','Government Revenue'),('PUBLIC_FIN','SUB-PUBLIC_FIN-002','Government Expenditure'),('PUBLIC_FIN','SUB-PUBLIC_FIN-003','Fiscal Deficit'),('PUBLIC_FIN','SUB-PUBLIC_FIN-004','Primary Deficit'),('PUBLIC_FIN','SUB-PUBLIC_FIN-005','Public Debt'),('PUBLIC_FIN','SUB-PUBLIC_FIN-006','Tax Revenue'),('PUBLIC_FIN','SUB-PUBLIC_FIN-007','Non-Tax Revenue'),('PUBLIC_FIN','SUB-PUBLIC_FIN-008','Capital Expenditure'),('PUBLIC_FIN','SUB-PUBLIC_FIN-009','Revenue Expenditure'),('PUBLIC_FIN','SUB-PUBLIC_FIN-010','Subsidies'),('PUBLIC_FIN','SUB-PUBLIC_FIN-011','Transfers'),('PUBLIC_FIN','SUB-PUBLIC_FIN-012','Guarantees'),('PUBLIC_FIN','SUB-PUBLIC_FIN-013','Public Assets'),('PUBLIC_FIN','SUB-PUBLIC_FIN-014','Disinvestment'),('PUBLIC_FIN','SUB-PUBLIC_FIN-015','Fiscal Sustainability'),
('TAX','SUB-TAX-001','GST'),('TAX','SUB-TAX-002','Direct Tax'),('TAX','SUB-TAX-003','Corporate Tax'),('TAX','SUB-TAX-004','Income Tax'),('TAX','SUB-TAX-005','Customs'),('TAX','SUB-TAX-006','Excise'),('TAX','SUB-TAX-007','Tax Administration'),('TAX','SUB-TAX-008','Tax Compliance'),('TAX','SUB-TAX-009','Tax Base'),('TAX','SUB-TAX-010','Formalisation'),('TAX','SUB-TAX-011','Digital Tax Administration'),
('BFS','SUB-BFS-001','Banking'),('BFS','SUB-BFS-002','Public Sector Banks'),('BFS','SUB-BFS-003','Private Banks'),('BFS','SUB-BFS-004','NPA'),('BFS','SUB-BFS-005','Insolvency'),('BFS','SUB-BFS-006','Credit'),('BFS','SUB-BFS-007','Financial Inclusion'),('BFS','SUB-BFS-008','Insurance'),('BFS','SUB-BFS-009','Pension'),('BFS','SUB-BFS-010','Capital Markets'),('BFS','SUB-BFS-011','Mutual Funds'),('BFS','SUB-BFS-012','FinTech'),('BFS','SUB-BFS-013','Digital Payments'),
('MFG','SUB-MFG-001','General Manufacturing'),('MFG','SUB-MFG-002','Electronics'),('MFG','SUB-MFG-003','Semiconductors'),('MFG','SUB-MFG-004','Automobiles'),('MFG','SUB-MFG-005','Auto Components'),('MFG','SUB-MFG-006','Textiles'),('MFG','SUB-MFG-007','Pharmaceuticals'),('MFG','SUB-MFG-008','Chemicals'),('MFG','SUB-MFG-009','Steel'),('MFG','SUB-MFG-010','Cement'),('MFG','SUB-MFG-011','Capital Goods'),('MFG','SUB-MFG-012','Defence Manufacturing'),('MFG','SUB-MFG-013','Machinery'),('MFG','SUB-MFG-014','Consumer Goods'),
('MSME','SUB-MSME-001','MSME Formation'),('MSME','SUB-MSME-002','MSME Credit'),('MSME','SUB-MSME-003','MSME Formalisation'),('MSME','SUB-MSME-004','MSME Employment'),('MSME','SUB-MSME-005','MSME Exports'),('MSME','SUB-MSME-006','Digitalisation'),('MSME','SUB-MSME-007','Government Procurement'),('MSME','SUB-MSME-008','Delayed Payments'),('MSME','SUB-MSME-009','Insolvency'),('MSME','SUB-MSME-010','Productivity'),
('AGRI','SUB-AGRI-001','Crop Production'),('AGRI','SUB-AGRI-002','Agricultural Productivity'),('AGRI','SUB-AGRI-003','Irrigation'),('AGRI','SUB-AGRI-004','Fertiliser'),('AGRI','SUB-AGRI-005','Seeds'),('AGRI','SUB-AGRI-006','Mechanisation'),('AGRI','SUB-AGRI-007','Agricultural Credit'),('AGRI','SUB-AGRI-008','Crop Insurance'),('AGRI','SUB-AGRI-009','MSP'),('AGRI','SUB-AGRI-010','Agricultural Markets'),('AGRI','SUB-AGRI-011','e-NAM'),('AGRI','SUB-AGRI-012','Food Processing'),('AGRI','SUB-AGRI-013','Storage'),('AGRI','SUB-AGRI-014','Cold Chain'),('AGRI','SUB-AGRI-015','Farmer Income'),('AGRI','SUB-AGRI-016','Agricultural Exports'),
('RURAL','SUB-RURAL-001','Rural Employment'),('RURAL','SUB-RURAL-002','Rural Income'),('RURAL','SUB-RURAL-003','Rural Roads'),('RURAL','SUB-RURAL-004','Rural Housing'),('RURAL','SUB-RURAL-005','Rural Electrification'),('RURAL','SUB-RURAL-006','Rural Water'),('RURAL','SUB-RURAL-007','Sanitation'),('RURAL','SUB-RURAL-008','Financial Inclusion'),('RURAL','SUB-RURAL-009','Digital Connectivity'),('RURAL','SUB-RURAL-010','Rural Enterprises'),
('SRV','SUB-SRV-001','IT'),('SRV','SUB-SRV-002','ITES'),('SRV','SUB-SRV-003','Professional Services'),('SRV','SUB-SRV-004','Financial Services'),('SRV','SUB-SRV-005','Healthcare Services'),('SRV','SUB-SRV-006','Education Services'),('SRV','SUB-SRV-007','Tourism'),('SRV','SUB-SRV-008','Hospitality'),('SRV','SUB-SRV-009','Retail'),('SRV','SUB-SRV-010','Logistics'),('SRV','SUB-SRV-011','Business Services'),
('DIGITAL','SUB-DIGITAL-001','Digital Public Infrastructure'),('DIGITAL','SUB-DIGITAL-002','Aadhaar'),('DIGITAL','SUB-DIGITAL-003','UPI'),('DIGITAL','SUB-DIGITAL-004','ONDC'),('DIGITAL','SUB-DIGITAL-005','Account Aggregator'),('DIGITAL','SUB-DIGITAL-006','DigiLocker'),('DIGITAL','SUB-DIGITAL-007','Digital Identity'),('DIGITAL','SUB-DIGITAL-008','Digital Payments'),('DIGITAL','SUB-DIGITAL-009','E-Governance'),('DIGITAL','SUB-DIGITAL-010','Digital Commerce'),('DIGITAL','SUB-DIGITAL-011','AI'),('DIGITAL','SUB-DIGITAL-012','Cloud'),('DIGITAL','SUB-DIGITAL-013','Cybersecurity'),
('STARTUPS','SUB-STARTUPS-001','Startup Formation'),('STARTUPS','SUB-STARTUPS-002','Startup Funding'),('STARTUPS','SUB-STARTUPS-003','Startup Survival'),('STARTUPS','SUB-STARTUPS-004','Unicorns'),('STARTUPS','SUB-STARTUPS-005','Deep Tech'),('STARTUPS','SUB-STARTUPS-006','Government Procurement'),('STARTUPS','SUB-STARTUPS-007','Startup Employment'),('STARTUPS','SUB-STARTUPS-008','Innovation'),('STARTUPS','SUB-STARTUPS-009','Venture Capital'),
('TRADE','SUB-TRADE-001','Merchandise Exports'),('TRADE','SUB-TRADE-002','Services Exports'),('TRADE','SUB-TRADE-003','Imports'),('TRADE','SUB-TRADE-004','Trade Balance'),('TRADE','SUB-TRADE-005','Trade Agreements'),('TRADE','SUB-TRADE-006','Export Competitiveness'),('TRADE','SUB-TRADE-007','Export Diversification'),('TRADE','SUB-TRADE-008','Global Value Chains'),('TRADE','SUB-TRADE-009','Logistics'),('TRADE','SUB-TRADE-010','Trade Facilitation'),
('INVEST','SUB-INVEST-001','FDI'),('INVEST','SUB-INVEST-002','FPI'),('INVEST','SUB-INVEST-003','Domestic Private Investment'),('INVEST','SUB-INVEST-004','Public Investment'),('INVEST','SUB-INVEST-005','Household Investment'),('INVEST','SUB-INVEST-006','Infrastructure Investment'),('INVEST','SUB-INVEST-007','Manufacturing Investment'),
('LABOUR','SUB-LABOUR-001','LFPR'),('LABOUR','SUB-LABOUR-002','WPR'),('LABOUR','SUB-LABOUR-003','Unemployment'),('LABOUR','SUB-LABOUR-004','Female Employment'),('LABOUR','SUB-LABOUR-005','Youth Employment'),('LABOUR','SUB-LABOUR-006','Formal Employment'),('LABOUR','SUB-LABOUR-007','Informal Employment'),('LABOUR','SUB-LABOUR-008','Real Wages'),('LABOUR','SUB-LABOUR-009','Labour Productivity'),('LABOUR','SUB-LABOUR-010','Labour Codes'),('LABOUR','SUB-LABOUR-011','Social Security'),('LABOUR','SUB-LABOUR-012','Gig Economy'),('LABOUR','SUB-LABOUR-013','Migration'),('LABOUR','SUB-LABOUR-014','Skills'),
('INFRA','SUB-INFRA-001','Roads'),('INFRA','SUB-INFRA-002','Highways'),('INFRA','SUB-INFRA-003','Expressways'),('INFRA','SUB-INFRA-004','Railways'),('INFRA','SUB-INFRA-005','Metro'),('INFRA','SUB-INFRA-006','Ports'),('INFRA','SUB-INFRA-007','Inland Waterways'),('INFRA','SUB-INFRA-008','Airports'),('INFRA','SUB-INFRA-009','Aviation'),('INFRA','SUB-INFRA-010','Logistics'),('INFRA','SUB-INFRA-011','Warehousing'),('INFRA','SUB-INFRA-012','Industrial Corridors'),('INFRA','SUB-INFRA-013','Urban Infrastructure'),('INFRA','SUB-INFRA-014','Rural Infrastructure'),
('ENERGY','SUB-ENERGY-001','Electricity'),('ENERGY','SUB-ENERGY-002','Generation'),('ENERGY','SUB-ENERGY-003','Transmission'),('ENERGY','SUB-ENERGY-004','Distribution'),('ENERGY','SUB-ENERGY-005','Renewable Energy'),('ENERGY','SUB-ENERGY-006','Solar'),('ENERGY','SUB-ENERGY-007','Wind'),('ENERGY','SUB-ENERGY-008','Hydro'),('ENERGY','SUB-ENERGY-009','Nuclear'),('ENERGY','SUB-ENERGY-010','Coal'),('ENERGY','SUB-ENERGY-011','Oil'),('ENERGY','SUB-ENERGY-012','Gas'),('ENERGY','SUB-ENERGY-013','Energy Security'),('ENERGY','SUB-ENERGY-014','Energy Efficiency'),('ENERGY','SUB-ENERGY-015','Electric Vehicles'),
('TELECOM','SUB-TELECOM-001','Mobile Subscribers'),('TELECOM','SUB-TELECOM-002','Internet'),('TELECOM','SUB-TELECOM-003','Broadband'),('TELECOM','SUB-TELECOM-004','4G'),('TELECOM','SUB-TELECOM-005','5G'),('TELECOM','SUB-TELECOM-006','Fibre'),('TELECOM','SUB-TELECOM-007','Data Centres'),('TELECOM','SUB-TELECOM-008','Telecom Manufacturing'),('TELECOM','SUB-TELECOM-009','Rural Connectivity'),('TELECOM','SUB-TELECOM-010','Spectrum'),
('HEALTH','SUB-HEALTH-001','Health Expenditure'),('HEALTH','SUB-HEALTH-002','Public Health'),('HEALTH','SUB-HEALTH-003','Hospitals'),('HEALTH','SUB-HEALTH-004','Primary Healthcare'),('HEALTH','SUB-HEALTH-005','Health Insurance'),('HEALTH','SUB-HEALTH-006','Pharmaceuticals'),('HEALTH','SUB-HEALTH-007','Medical Devices'),('HEALTH','SUB-HEALTH-008','Maternal Health'),('HEALTH','SUB-HEALTH-009','Child Health'),('HEALTH','SUB-HEALTH-010','Nutrition'),('HEALTH','SUB-HEALTH-011','Life Expectancy'),('HEALTH','SUB-HEALTH-012','Disease Burden'),('HEALTH','SUB-HEALTH-013','Digital Health'),
('EDU','SUB-EDU-001','School Education'),('EDU','SUB-EDU-002','Higher Education'),('EDU','SUB-EDU-003','Vocational Education'),('EDU','SUB-EDU-004','Universities'),('EDU','SUB-EDU-005','Enrolment'),('EDU','SUB-EDU-006','Learning Outcomes'),('EDU','SUB-EDU-007','Literacy'),('EDU','SUB-EDU-008','Digital Education'),('EDU','SUB-EDU-009','Research'),('EDU','SUB-EDU-010','Skills'),('EDU','SUB-EDU-011','Employability'),
('HOUSING','SUB-HOUSING-001','Housing Construction'),('HOUSING','SUB-HOUSING-002','Affordable Housing'),('HOUSING','SUB-HOUSING-003','Rural Housing'),('HOUSING','SUB-HOUSING-004','Urban Housing'),('HOUSING','SUB-HOUSING-005','Housing Finance'),('HOUSING','SUB-HOUSING-006','Slum Development'),('HOUSING','SUB-HOUSING-007','Basic Amenities'),
('WATER','SUB-WATER-001','Drinking Water'),('WATER','SUB-WATER-002','Tap Connections'),('WATER','SUB-WATER-003','Irrigation'),('WATER','SUB-WATER-004','Sewage'),('WATER','SUB-WATER-005','Sanitation'),('WATER','SUB-WATER-006','Toilets'),('WATER','SUB-WATER-007','Wastewater'),('WATER','SUB-WATER-008','Water Security'),
('STI','SUB-STI-001','R&D'),('STI','SUB-STI-002','Patents'),('STI','SUB-STI-003','Scientific Publications'),('STI','SUB-STI-004','Deep Tech'),('STI','SUB-STI-005','Biotechnology'),('STI','SUB-STI-006','AI'),('STI','SUB-STI-007','Quantum'),('STI','SUB-STI-008','Space Technology'),('STI','SUB-STI-009','Defence Technology'),('STI','SUB-STI-010','Industrial Technology'),
('SPACE','SUB-SPACE-001','Launches'),('SPACE','SUB-SPACE-002','Satellites'),('SPACE','SUB-SPACE-003','Commercial Space'),('SPACE','SUB-SPACE-004','Human Spaceflight'),('SPACE','SUB-SPACE-005','Navigation'),('SPACE','SUB-SPACE-006','Earth Observation'),('SPACE','SUB-SPACE-007','Space Startups'),('SPACE','SUB-SPACE-008','Space Infrastructure'),
('DEFENCE','SUB-DEFENCE-001','Defence Expenditure'),('DEFENCE','SUB-DEFENCE-002','Defence Production'),('DEFENCE','SUB-DEFENCE-003','Defence Exports'),('DEFENCE','SUB-DEFENCE-004','Procurement'),('DEFENCE','SUB-DEFENCE-005','Indigenisation'),('DEFENCE','SUB-DEFENCE-006','R&D'),('DEFENCE','SUB-DEFENCE-007','Armed Forces Modernisation'),('DEFENCE','SUB-DEFENCE-008','Strategic Capability'),
('ENV','SUB-ENV-001','Air Quality'),('ENV','SUB-ENV-002','Water Quality'),('ENV','SUB-ENV-003','Forest Cover'),('ENV','SUB-ENV-004','Biodiversity'),('ENV','SUB-ENV-005','Emissions'),('ENV','SUB-ENV-006','Renewable Energy'),('ENV','SUB-ENV-007','Climate Finance'),('ENV','SUB-ENV-008','Waste Management'),('ENV','SUB-ENV-009','Environmental Regulation'),
('TOURISM','SUB-TOURISM-001','Domestic Tourism'),('TOURISM','SUB-TOURISM-002','Foreign Tourist Arrivals'),('TOURISM','SUB-TOURISM-003','Tourism Revenue'),('TOURISM','SUB-TOURISM-004','Infrastructure'),('TOURISM','SUB-TOURISM-005','Employment'),('TOURISM','SUB-TOURISM-006','Medical Tourism'),('TOURISM','SUB-TOURISM-007','Religious Tourism'),('TOURISM','SUB-TOURISM-008','Cultural Tourism'),
('SOCIAL','SUB-SOCIAL-001','Food Security'),('SOCIAL','SUB-SOCIAL-002','Pensions'),('SOCIAL','SUB-SOCIAL-003','Direct Benefit Transfers'),('SOCIAL','SUB-SOCIAL-004','Social Insurance'),('SOCIAL','SUB-SOCIAL-005','Welfare Schemes'),('SOCIAL','SUB-SOCIAL-006','Rural Employment'),('SOCIAL','SUB-SOCIAL-007','Disability Support'),('SOCIAL','SUB-SOCIAL-008','Senior Citizens'),
('POVERTY','SUB-POVERTY-001','Poverty'),('POVERTY','SUB-POVERTY-002','Multidimensional Poverty'),('POVERTY','SUB-POVERTY-003','Consumption'),('POVERTY','SUB-POVERTY-004','Income'),('POVERTY','SUB-POVERTY-005','Real Wages'),('POVERTY','SUB-POVERTY-006','Household Assets'),('POVERTY','SUB-POVERTY-007','Electricity'),('POVERTY','SUB-POVERTY-008','Housing'),('POVERTY','SUB-POVERTY-009','Sanitation'),('POVERTY','SUB-POVERTY-010','Water'),('POVERTY','SUB-POVERTY-011','Banking'),('POVERTY','SUB-POVERTY-012','Insurance'),('POVERTY','SUB-POVERTY-013','Digital Access'),
('WOMEN','SUB-WOMEN-001','Female LFPR'),('WOMEN','SUB-WOMEN-002','Female Employment'),('WOMEN','SUB-WOMEN-003','Entrepreneurship'),('WOMEN','SUB-WOMEN-004','Financial Inclusion'),('WOMEN','SUB-WOMEN-005','Education'),('WOMEN','SUB-WOMEN-006','Health'),('WOMEN','SUB-WOMEN-007','Maternal Outcomes'),('WOMEN','SUB-WOMEN-008','Safety'),('WOMEN','SUB-WOMEN-009','Property Ownership'),('WOMEN','SUB-WOMEN-010','Digital Inclusion'),
('DEMOGRAPHICS','SUB-DEMOGRAPHICS-001','Population'),('DEMOGRAPHICS','SUB-DEMOGRAPHICS-002','Age Structure'),('DEMOGRAPHICS','SUB-DEMOGRAPHICS-003','Dependency Ratio'),('DEMOGRAPHICS','SUB-DEMOGRAPHICS-004','Fertility'),('DEMOGRAPHICS','SUB-DEMOGRAPHICS-005','Mortality'),('DEMOGRAPHICS','SUB-DEMOGRAPHICS-006','Urbanisation'),('DEMOGRAPHICS','SUB-DEMOGRAPHICS-007','Migration'),('DEMOGRAPHICS','SUB-DEMOGRAPHICS-008','Working-Age Population'),
('GOV','SUB-GOV-001','Administrative Reform'),('GOV','SUB-GOV-002','Digital Governance'),('GOV','SUB-GOV-003','Procurement'),('GOV','SUB-GOV-004','Transparency'),('GOV','SUB-GOV-005','Anti-Corruption'),('GOV','SUB-GOV-006','Regulatory Reform'),('GOV','SUB-GOV-007','Civil Services'),('GOV','SUB-GOV-008','Federal Institutions'),('GOV','SUB-GOV-009','Public Service Delivery'),
('LEGAL','SUB-LEGAL-001','Commercial Law'),('LEGAL','SUB-LEGAL-002','Insolvency'),('LEGAL','SUB-LEGAL-003','Labour Law'),('LEGAL','SUB-LEGAL-004','Tax Law'),('LEGAL','SUB-LEGAL-005','Corporate Law'),('LEGAL','SUB-LEGAL-006','Criminal Law'),('LEGAL','SUB-LEGAL-007','Environmental Law'),('LEGAL','SUB-LEGAL-008','Regulatory Law'),('LEGAL','SUB-LEGAL-009','Judicial Decisions Affecting Economic Policy'),
('GLOBAL','SUB-GLOBAL-001','GDP Rank'),('GLOBAL','SUB-GLOBAL-002','GDP Per Capita'),('GLOBAL','SUB-GLOBAL-003','Trade'),('GLOBAL','SUB-GLOBAL-004','FDI'),('GLOBAL','SUB-GLOBAL-005','Foreign Exchange Reserves'),('GLOBAL','SUB-GLOBAL-006','Global Competitiveness'),('GLOBAL','SUB-GLOBAL-007','Strategic Economy'),('GLOBAL','SUB-GLOBAL-008','International Institutions'),('GLOBAL','SUB-GLOBAL-009','Global Supply Chains')
) AS v(sector_code,code,name)
JOIN tracker.sectors s ON s.code=v.sector_code
CROSS JOIN tracker.taxonomy_versions tv WHERE tv.version_code='TAXONOMY-1.0';

COMMIT;
