BEGIN;

CREATE TABLE tracker.controlled_vocabularies (
    vocabulary_code VARCHAR(96) NOT NULL,
    value_code VARCHAR(96) NOT NULL,
    display_label TEXT NOT NULL,
    description TEXT,
    sort_order INTEGER,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive','deprecated')),
    PRIMARY KEY (vocabulary_code, value_code)
);

INSERT INTO tracker.controlled_vocabularies (vocabulary_code,value_code,display_label,description,sort_order) VALUES
('materiality','P1','P1',NULL,1),
('materiality','P2','P2',NULL,2),
('materiality','P3','P3',NULL,3),
('materiality','P4','P4',NULL,4),
('materiality','P5','P5',NULL,5),
('source_tier','T1','Tier 1','Primary official source.',1),
('source_tier','T2','Tier 2','Official international institution.',2),
('source_tier','T3','Tier 3','Peer-reviewed academic research.',3),
('source_tier','T4','Tier 4','Credible research institution or industry body.',4),
('source_tier','T5','Tier 5','Reputable journalism.',5),
('source_tier','T6','Tier 6','Secondary database or aggregator.',6),
('source_tier','T7','Tier 7','Social media or commentary.',7),
('evidence_grade','A','A','Primary authoritative evidence.',1),
('evidence_grade','B','B','Strong institutional evidence.',2),
('evidence_grade','C','C','Credible secondary evidence.',3),
('evidence_grade','D','D','Weak or unverified evidence.',4),
('confidence','HIGH','High',NULL,1),
('confidence','MODERATE','Moderate',NULL,2),
('confidence','LOW','Low',NULL,3),
('confidence','INDETERMINATE','Indeterminate',NULL,4),
('attribution_grade','A','A','Strong causal evidence.',1),
('attribution_grade','B','B','Good causal evidence.',2),
('attribution_grade','C','C','Plausible contribution, limited identification.',3),
('attribution_grade','D','D','Insufficient causal evidence.',4),
('policy_verdict','HIGHLY_EFFECTIVE','Highly effective',NULL,1),
('policy_verdict','EFFECTIVE','Effective',NULL,2),
('policy_verdict','PARTIALLY_EFFECTIVE','Partially effective',NULL,3),
('policy_verdict','INEFFECTIVE','Ineffective',NULL,4),
('policy_verdict','COUNTERPRODUCTIVE','Counterproductive',NULL,5),
('policy_verdict','INDETERMINATE','Indeterminate',NULL,6),
('implementation_verdict','EXCELLENT','Excellent',NULL,1),
('implementation_verdict','STRONG','Strong',NULL,2),
('implementation_verdict','ADEQUATE','Adequate',NULL,3),
('implementation_verdict','WEAK','Weak',NULL,4),
('implementation_verdict','FAILED','Failed',NULL,5),
('implementation_verdict','INDETERMINATE','Indeterminate',NULL,6),
('government_contribution','HIGH','High',NULL,1),
('government_contribution','MODERATE','Moderate',NULL,2),
('government_contribution','LIMITED','Limited',NULL,3),
('government_contribution','MINIMAL','Minimal',NULL,4),
('government_contribution','NEGATIVE','Negative',NULL,5),
('government_contribution','INDETERMINATE','Indeterminate',NULL,6),
('outcome_classification','TRANSFORMATIONAL_SUCCESS','Transformational success',NULL,1),
('outcome_classification','MAJOR_SUCCESS','Major success',NULL,2),
('outcome_classification','MODERATE_SUCCESS','Moderate success',NULL,3),
('outcome_classification','LIMITED_SUCCESS','Limited success',NULL,4),
('outcome_classification','MIXED_OUTCOME','Mixed outcome',NULL,5),
('outcome_classification','UNDERPERFORMING','Underperforming',NULL,6),
('outcome_classification','FAILURE','Failure',NULL,7),
('outcome_classification','TOO_EARLY','Too early',NULL,8),
('outcome_classification','INSUFFICIENT_EVIDENCE','Insufficient evidence',NULL,9),
('sector_verdict','STRONG_IMPROVEMENT','Strong improvement',NULL,1),
('sector_verdict','MODERATE_IMPROVEMENT','Moderate improvement',NULL,2),
('sector_verdict','LIMITED_IMPROVEMENT','Limited improvement',NULL,3),
('sector_verdict','MIXED','Mixed',NULL,4),
('sector_verdict','STAGNATION','Stagnation',NULL,5),
('sector_verdict','DETERIORATION','Deterioration',NULL,6),
('research_status','NOT_STARTED','Not Started',NULL,1),
('research_status','DISCOVERY','Discovery',NULL,2),
('research_status','EVIDENCE_COLLECTION','Evidence Collection',NULL,3),
('research_status','DATA_EXTRACTION','Data Extraction',NULL,4),
('research_status','ANALYSIS','Analysis',NULL,5),
('research_status','ATTRIBUTION','Attribution',NULL,6),
('research_status','REVIEW','Review',NULL,7),
('research_status','VERIFIED','Verified',NULL,8),
('research_status','PUBLISHED','Published',NULL,9),
('research_status','NEEDS_REVISION','Needs Revision',NULL,10),
('research_status','SUPERSEDED','Superseded',NULL,11),
('publication_status','DRAFT','Draft',NULL,1),
('publication_status','INTERNAL_REVIEW','Internal Review',NULL,2),
('publication_status','VERIFIED','Verified',NULL,3),
('publication_status','PUBLISHED','Published',NULL,4),
('publication_status','CORRECTED','Corrected',NULL,5),
('publication_status','SUPERSEDED','Superseded',NULL,6),
('data_status','RAW','Raw',NULL,1),
('data_status','EXTRACTED','Extracted',NULL,2),
('data_status','VALIDATED','Validated',NULL,3),
('data_status','RECONCILED','Reconciled',NULL,4),
('data_status','VERIFIED','Verified',NULL,5),
('data_status','ESTIMATED','Estimated',NULL,6),
('data_status','PROXY','Proxy',NULL,7),
('data_status','REVISED','Revised',NULL,8),
('data_status','SUPERSEDED','Superseded',NULL,9),
('data_status','DISPUTED','Disputed',NULL,10),
('data_status','UNAVAILABLE','Unavailable',NULL,11),
('counterfactual_method','CF1','Historical trend',NULL,1),
('counterfactual_method','CF2','Pre-policy trend',NULL,2),
('counterfactual_method','CF3','International peer',NULL,3),
('counterfactual_method','CF4','State comparison',NULL,4),
('counterfactual_method','CF5','Sector comparison',NULL,5),
('counterfactual_method','CF6','Difference-in-differences',NULL,6),
('counterfactual_method','CF7','Synthetic control',NULL,7),
('counterfactual_method','CF8','Natural experiment',NULL,8),
('counterfactual_method','CF9','Academic estimate',NULL,9),
('counterfactual_method','CF10','Multiple methods',NULL,10),
('counterfactual_method','CF11','No credible counterfactual available',NULL,11);

COMMIT;
